micronaut:
  server:
    cors:
      configurations:
        default:
          allowed-origins:
            - ec2-98-80-145-93.compute-1.amazonaws.com

auth:
  cookie:
    secure: true
    same-site: None
