micronaut:
  application:
    name: auth-service
  openapi:
    target:
      file: openapi-auth.yml
  server:
    port: ${MICRONAUT_SERVER_PORT:8081}
    cors:
      enabled: true
      configurations:
        default:
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Authorization
            - Content-Type
            - authorization
            - content-type
          exposed-headers:
            - Location
          allow-credentials: true

datasources:
  default:
    db-type: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 5
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: false
        format_sql: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000} # 15 min
  refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7 days

auth:
  cookie:
    path: /
