micronaut:
  application:
    name: temperature-service
  openapi:
    target:
      file: openapi-temperature.yml
  server:
    port: ${MICRONAUT_SERVER_PORT:8082}
    cors:
      enabled: true
      configurations:
        default:
          allowed-origins:
            - http://localhost:5173
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Authorization
            - Content-Type
          exposed-headers:
            - Location

datasources:
  default:
    db-type: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 5
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: false
        format_sql: false

jwt:
  secret: ${JWT_SECRET}
